Adding a module that retirves passwords from Amazon's Parameter Store
saltstack/salt-contrib pull request #185
Opened 2018-01-25 21:34 UTC by Ramdog69

Salt module that retrieves a key stored in Amazon's Parameter store.
https://docs.aws.amazon.com/systems-manager/latest/userguide/systems-manager-paramstore.html/

2018-04-10 21:02 UTC, UtahDave requested changes
Thanks so much for the addition!  Could you review the requested changes?  Thanks!

2018-04-10 21:02 UTC, UtahDave commented on modules/awsparam.py
> +#! /usr/bin/env python
No need for the shebang.  Please replace it with 
```# -*- coding: utf-8 -*-```

2018-04-10 21:02 UTC, UtahDave commented on modules/awsparam.py
> +"""Salt module that retrieves a key stored in Amazon's Parameter store.
Please standardize multi-line comments to use triple single quotes instead of triple double quotes.

2018-04-10 21:02 UTC, UtahDave commented on modules/awsparam.py
> +  '''Get a parametewr by name.'''
We prefer the triple single quotes be on their own lines like this:
```
'''
Get a parameter by name.
'''
```

Also, please fix `parameter` misspelling.

2018-04-10 21:02 UTC, UtahDave commented on modules/awsparam.py
> +  '''Get a parametewr by name.'''
Per pep8, please use 4 spaces for each indentation level.

2018-04-13 11:33 UTC, Ramdog69 commented
Ok, I've made the requested changes.  Please let me know if there is anything else you would like to see.

Thanks!

2018-04-19 17:48 UTC, dwoz commented
@UtahDave Do the changes look satisfactory?

2018-06-01 17:32 UTC, UtahDave approved these changes

2018-06-01 17:32 UTC, UtahDave commented
Thanks for the updates!

2018-06-01 17:32 UTC, merged

2019-03-26 07:00 UTC, mchugh19 commented
SSM was added for the Neon release here: saltstack/salt#50215

If there is any missing functionality, please feel free to collaborate on it upstream.